React accordion component
shawnkost/c1120-code-solutions pull request #128
Opened 2021-01-21 22:09 UTC by shawnkost

![react-accordion](https://user-images.githubusercontent.com/71413368/105418502-16f06a80-5bf2-11eb-8626-9928a936bebd.gif)

2021-01-21 23:10 UTC, scbowler requested changes
Some updates needed, let us know if you have any questions

2021-01-21 23:10 UTC, scbowler commented on react-accordion-component/src/accordion.jsx
> +  return <div className="hide">{props.value.details}</div>
Here you can compare the `id` stored in state with the `id` of the item, if the ids match that is the open item and add a class of `show`, if the ids do not match add a class of `hide`

2021-01-21 23:10 UTC, scbowler commented on react-accordion-component/src/accordion.jsx
> +        <TopicName key={topic.name} value={topic} test={props.test} />
Here you can save the correct id with the click handler, In the below example I will use your names but you need to change the prop name from `test` to something more appropriate. Also make sure to use something unique for the `key` prop like an `id`, `name` is not guaranteed to be unique

```JSX
<TopicName key={topic.id} value={topic} test={() => props.test(topic.id)} />
```

2021-01-21 23:10 UTC, scbowler commented on react-accordion-component/src/index.jsx
> +  },
Each item needs an `id` property that is unique

2021-01-21 23:53 UTC, shawnkost commented on react-accordion-component/src/accordion.jsx
> +        <TopicName key={topic.name} value={topic} test={props.test} />
I'm confused on what the included snippet is doing, and how I can access this within handleClick(). I have attached a photo of my updated code. 

`test={() => props.test(topic.id)}`

![updated-code](https://user-images.githubusercontent.com/71413368/105426818-b4529b00-5c00-11eb-9516-19f2b2ced980.png)

2021-01-22 00:00 UTC, scbowler commented on react-accordion-component/src/accordion.jsx
> +        <TopicName key={topic.name} value={topic} test={props.test} />
In `handleClick` `event` should now be the `id` of the item clicked on. Try just console logging event without the `target` property within `handleClick` it should be the id. You'll want to update the name of the parameter to reflect that. Then you just need to save the `id` into state.

2021-01-22 00:53 UTC, scbowler approved these changes
Much better! Looks great! 👍 

FYI: you can accomplish the same thing with just one property in state.... 😄

2021-01-22 02:12 UTC, merged