Completed React carousel component | Shawn Kost
shawnkost/c1120-code-solutions pull request #129
Opened 2021-01-22 03:43 UTC by shawnkost

![react-carousel](https://user-images.githubusercontent.com/71413368/105443585-ea077c00-5c20-11eb-9e65-e127c702e1ac.gif)

2021-01-26 01:06 UTC, scbowler requested changes
Great job getting this to work! Just a couple small things that you can do to clean some stuff up. Let me know if you have any questions about the requested changes!

2021-01-26 01:06 UTC, scbowler commented on react-carousel-component/src/carousel.jsx
> +    this.state = { currentPhotoId: 1, timeoutId: null };
The `timeoutId` doesn't really need to be stored in `state`, it can just be stored in a property of `this`. It is not directly effecting what is being rendered.

2021-01-26 01:06 UTC, scbowler commented on react-carousel-component/dist/styles.css
> +}
It is not good to directly target classnames in your css that come from a 3rd party library. You are changing its default behavior which can cause issues with other programmers working on the project or even yourself down the road. Not a big deal here but not a good habit to develop.

2021-01-26 01:06 UTC, scbowler commented on react-carousel-component/dist/styles.css
> +.fa-circle {
Same as above you shouldn't directly target 3rd party classes

2021-01-26 19:00 UTC, scbowler requested changes
Looking good, a few more changes needed. It is easier to use the images `index` in state to control which image is being displayed. Indexes are always in order and it makes it easier for your carousel to work with any array size. As always let me know if you have any questions!

2021-01-26 19:26 UTC, shawnkost commented on react-carousel-component/src/carousel.jsx
> +  }
I'm confused on how I can pass index to state within this function. If I pass the whole image parameter from const Circles, the value will just be the individual image, how can I tell what index it would be? Photos attached for reference.

![image](https://user-images.githubusercontent.com/71413368/105894488-2e9c6a00-5fc9-11eb-8233-f6b2fc96843f.png)
![image](https://user-images.githubusercontent.com/71413368/105894557-407e0d00-5fc9-11eb-8b47-de2c60ca4a53.png)
![image](https://user-images.githubusercontent.com/71413368/105894613-5095ec80-5fc9-11eb-95dd-e7161366d672.png)

2021-01-26 19:34 UTC, scbowler commented on react-carousel-component/src/carousel.jsx
> +  }
For the callback function of `map` you can give it a second parameter that will be the index of the item. You can use that index to pass into `props.specificPhoto(index)`

2021-01-27 23:04 UTC, scbowler approved these changes
Looks good! 👍

2021-01-28 20:41 UTC, merged